import { db, gyms, fighters, tournaments } from "@workspace/db";

async function seed() {
  console.log("Seeding BC / Western Canada community data...");

  // ── Gyms ──────────────────────────────────────────────────────────────────
  const insertedGyms = await db.insert(gyms).values([
    {
      name: "Vancouver Boxing Club",
      city: "Vancouver",
      state: "BC",
      country: "Canada",
      address: "285 E 5th Ave, Vancouver",
      phone: "(604) 555-0121",
      coachName: "Coach Danny Tran",
      foundedYear: 1991,
      activeMembers: 95,
      specialties: "Olympic-style amateur development, footwork, jab mastery",
    },
    {
      name: "Eastside Boxing Academy",
      city: "Vancouver",
      state: "BC",
      country: "Canada",
      address: "1240 Kingsway, Vancouver",
      phone: "(604) 555-0188",
      coachName: "Coach Marcus Reyes",
      foundedYear: 2003,
      activeMembers: 72,
      specialties: "Combination work, pressure fighting, amateur-to-pro pathway",
    },
    {
      name: "Pacific Rim Fight Centre",
      city: "Surrey",
      state: "BC",
      country: "Canada",
      address: "13515 King George Blvd, Surrey",
      phone: "(604) 555-0144",
      coachName: "Coach Harpreet Gill",
      foundedYear: 2009,
      activeMembers: 61,
      specialties: "Body work, conditioning, inside fighting",
    },
    {
      name: "Victoria Boxing Club",
      city: "Victoria",
      state: "BC",
      country: "Canada",
      address: "741 Burnside Rd W, Victoria",
      phone: "(250) 555-0163",
      coachName: "Coach Sean MacLeod",
      foundedYear: 1985,
      activeMembers: 54,
      specialties: "Classical technique, defence-first boxing, counter-punching",
    },
    {
      name: "Burnaby Fight Academy",
      city: "Burnaby",
      state: "BC",
      country: "Canada",
      address: "3883 Henning Dr, Burnaby",
      phone: "(604) 555-0109",
      coachName: "Coach Joanna Chen",
      foundedYear: 2014,
      activeMembers: 48,
      specialties: "Speed training, southpaw specialization, pro preparation",
    },
    {
      name: "Kelowna Boxing & Fitness",
      city: "Kelowna",
      state: "BC",
      country: "Canada",
      address: "1560 Water St, Kelowna",
      phone: "(250) 555-0177",
      coachName: "Coach Travis Belanger",
      foundedYear: 2007,
      activeMembers: 39,
      specialties: "Fitness boxing, amateur development, stamina conditioning",
    },
    {
      name: "Abbotsford Boxing Club",
      city: "Abbotsford",
      state: "BC",
      country: "Canada",
      address: "2070 Gladwin Rd, Abbotsford",
      phone: "(604) 555-0155",
      coachName: "Coach Lorne Mackenzie",
      foundedYear: 1999,
      activeMembers: 43,
      specialties: "Aggressive pressure style, heavyweight development",
    },
  ]).returning();

  const [vbc, eastside, pacificRim, victoriaBC, burnaby, kelowna, abbotsford] = insertedGyms;
  console.log(`Inserted ${insertedGyms.length} gyms`);

  // ── Fighters ─────────────────────────────────────────────────────────────
  await db.insert(fighters).values([
    // Lightweight – Amateur
    {
      name: "Tyler Nguyen",
      gymId: vbc.id,
      weightClass: "Lightweight",
      stance: "Orthodox",
      age: 20,
      status: "amateur",
      recordWins: 13,
      recordLosses: 2,
      recordDraws: 0,
      rankAmateur: 1,
      style: "counter",
      bio: "Technically precise counter-puncher, two-time BC Provincial champion.",
    },
    {
      name: "Jordan Chua",
      gymId: eastside.id,
      weightClass: "Lightweight",
      stance: "Southpaw",
      age: 19,
      status: "amateur",
      recordWins: 10,
      recordLosses: 3,
      recordDraws: 1,
      rankAmateur: 2,
      style: "aggressive",
      bio: "Southpaw pressure fighter with fast hands and relentless volume.",
    },
    {
      name: "Cody Belanger",
      gymId: kelowna.id,
      weightClass: "Lightweight",
      stance: "Orthodox",
      age: 22,
      status: "amateur",
      recordWins: 8,
      recordLosses: 4,
      recordDraws: 0,
      rankAmateur: 3,
      style: "brawler",
      bio: "High-output brawler who dictates pace with heavy jabs and overhand rights.",
    },
    {
      name: "Derek Santos",
      gymId: victoriaBC.id,
      weightClass: "Lightweight",
      stance: "Orthodox",
      age: 21,
      status: "amateur",
      recordWins: 7,
      recordLosses: 5,
      recordDraws: 0,
      rankAmateur: 4,
      style: "defensive",
      bio: "Slick defensive boxer known for his shoulder roll and sharp jab.",
    },
    // Lightweight – Pro
    {
      name: "Ryan 'Razor' Tran",
      gymId: vbc.id,
      weightClass: "Lightweight",
      stance: "Orthodox",
      age: 27,
      status: "pro",
      recordWins: 16,
      recordLosses: 3,
      recordDraws: 0,
      rankPro: 1,
      style: "counter",
      bio: "Western Canadian lightweight champion, known for his devastating right cross.",
    },
    {
      name: "Marco 'The Cobra' Delgado",
      gymId: burnaby.id,
      weightClass: "Lightweight",
      stance: "Southpaw",
      age: 29,
      status: "pro",
      recordWins: 12,
      recordLosses: 5,
      recordDraws: 1,
      rankPro: 2,
      style: "aggressive",
      bio: "Fast-starting southpaw who pins opponents on the ropes with relentless pressure.",
    },
    // Welterweight – Amateur
    {
      name: "Jaspreet Dhaliwal",
      gymId: pacificRim.id,
      weightClass: "Welterweight",
      stance: "Orthodox",
      age: 21,
      status: "amateur",
      recordWins: 15,
      recordLosses: 2,
      recordDraws: 0,
      rankAmateur: 1,
      style: "balanced",
      bio: "Surrey's top amateur welterweight with a textbook right-left combination and quick feet.",
    },
    {
      name: "Ethan MacKinnon",
      gymId: victoriaBC.id,
      weightClass: "Welterweight",
      stance: "Southpaw",
      age: 23,
      status: "amateur",
      recordWins: 11,
      recordLosses: 4,
      recordDraws: 1,
      rankAmateur: 2,
      style: "counter",
      bio: "Smooth southpaw from Victoria with excellent ring generalship.",
    },
    {
      name: "Brendan O'Neill",
      gymId: abbotsford.id,
      weightClass: "Welterweight",
      stance: "Orthodox",
      age: 20,
      status: "amateur",
      recordWins: 9,
      recordLosses: 4,
      recordDraws: 0,
      rankAmateur: 3,
      style: "aggressive",
      bio: "Abbotsford crowd favourite with knockout power and relentless aggression.",
    },
    // Welterweight – Pro
    {
      name: "Kevin 'Lightning' Park",
      gymId: eastside.id,
      weightClass: "Welterweight",
      stance: "Orthodox",
      age: 28,
      status: "pro",
      recordWins: 19,
      recordLosses: 4,
      recordDraws: 1,
      rankPro: 1,
      style: "counter",
      bio: "BC's premier welterweight, Canadian title contender with 14 stoppages.",
    },
    {
      name: "Damien 'The Hawk' Fortier",
      gymId: vbc.id,
      weightClass: "Welterweight",
      stance: "Orthodox",
      age: 30,
      status: "pro",
      recordWins: 14,
      recordLosses: 7,
      recordDraws: 0,
      rankPro: 2,
      style: "aggressive",
      bio: "Veteran pressure fighter who has campaigned across Western Canada and the US.",
    },
    // Middleweight – Amateur
    {
      name: "Luca Ferraro",
      gymId: vbc.id,
      weightClass: "Middleweight",
      stance: "Orthodox",
      age: 22,
      status: "amateur",
      recordWins: 17,
      recordLosses: 1,
      recordDraws: 0,
      rankAmateur: 1,
      style: "balanced",
      bio: "The most decorated amateur middleweight in BC, bound for national team.",
    },
    {
      name: "Nolan Swanson",
      gymId: burnaby.id,
      weightClass: "Middleweight",
      stance: "Southpaw",
      age: 20,
      status: "amateur",
      recordWins: 12,
      recordLosses: 3,
      recordDraws: 0,
      rankAmateur: 2,
      style: "counter",
      bio: "Converted southpaw with exceptional timing and a high fight IQ.",
    },
    {
      name: "Aiden Rousseau",
      gymId: kelowna.id,
      weightClass: "Middleweight",
      stance: "Orthodox",
      age: 24,
      status: "amateur",
      recordWins: 10,
      recordLosses: 5,
      recordDraws: 0,
      rankAmateur: 3,
      style: "brawler",
      bio: "Okanagan's toughest amateur, known for his iron chin and high work rate.",
    },
    // Middleweight – Pro
    {
      name: "Isaiah 'Iron' Campbell",
      gymId: eastside.id,
      weightClass: "Middleweight",
      stance: "Orthodox",
      age: 31,
      status: "pro",
      recordWins: 23,
      recordLosses: 5,
      recordDraws: 2,
      rankPro: 1,
      style: "aggressive",
      bio: "Canadian Middleweight Champion, devastating body puncher with 18 KOs.",
    },
    {
      name: "David 'Ghost' Leclair",
      gymId: victoriaBC.id,
      weightClass: "Middleweight",
      stance: "Orthodox",
      age: 29,
      status: "pro",
      recordWins: 18,
      recordLosses: 7,
      recordDraws: 1,
      rankPro: 2,
      style: "defensive",
      bio: "Elusive Victoria-based boxer with championship-level defence and sharp counters.",
    },
    // Heavyweight – Amateur
    {
      name: "Big Gord Mackenzie",
      gymId: abbotsford.id,
      weightClass: "Heavyweight",
      stance: "Orthodox",
      age: 23,
      status: "amateur",
      recordWins: 11,
      recordLosses: 1,
      recordDraws: 0,
      rankAmateur: 1,
      style: "brawler",
      bio: "Fraser Valley's most feared heavyweight amateur — nine first-round stoppages.",
    },
    {
      name: "Dmitri Volkov",
      gymId: vbc.id,
      weightClass: "Heavyweight",
      stance: "Orthodox",
      age: 25,
      status: "amateur",
      recordWins: 8,
      recordLosses: 3,
      recordDraws: 0,
      rankAmateur: 2,
      style: "balanced",
      bio: "Russian-Canadian heavyweight with classical European technique and heavy jab.",
    },
    // Heavyweight – Pro
    {
      name: "Carl 'The Bear' Leblanc",
      gymId: eastside.id,
      weightClass: "Heavyweight",
      stance: "Orthodox",
      age: 33,
      status: "pro",
      recordWins: 24,
      recordLosses: 4,
      recordDraws: 0,
      rankPro: 1,
      style: "aggressive",
      bio: "BC's most feared professional heavyweight with 21 KOs and a Canadian title belt.",
    },
  ]).returning();
  console.log(`Inserted ${insertedGyms.length} fighters`);

  // ── Tournaments ───────────────────────────────────────────────────────────
  await db.insert(tournaments).values([
    {
      name: "BC Provincial Boxing Championships",
      city: "Vancouver",
      state: "BC",
      venue: "PNE Forum, Vancouver",
      startDate: "2026-06-13",
      endDate: "2026-06-15",
      type: "amateur",
      status: "upcoming",
      weightClasses: "Flyweight, Lightweight, Welterweight, Middleweight, Light Heavyweight, Heavyweight",
      entryDeadline: "2026-05-30",
      maxParticipants: 120,
      registeredCount: 71,
      entryFee: 4000,
      description: "The premier amateur boxing championship in BC. Top finishers qualify for Boxing Canada Nationals.",
      contactEmail: "entries@bcboxing.ca",
      contactPhone: "(604) 555-0100",
    },
    {
      name: "Victoria Golden Gloves Open",
      city: "Victoria",
      state: "BC",
      venue: "Archie Browning Sports Centre",
      startDate: "2026-05-31",
      endDate: "2026-06-01",
      type: "amateur",
      status: "upcoming",
      weightClasses: "Lightweight, Welterweight, Middleweight, Heavyweight",
      entryDeadline: "2026-05-20",
      maxParticipants: 64,
      registeredCount: 58,
      entryFee: 3500,
      description: "One of Vancouver Island's longest-running amateur tournaments, open to all BC fighters.",
      contactEmail: "victoriagoldengloves@gmail.com",
      contactPhone: "(250) 555-0155",
    },
    {
      name: "Surrey Open Amateur Championships",
      city: "Surrey",
      state: "BC",
      venue: "Cloverdale Arena",
      startDate: "2026-07-19",
      endDate: "2026-07-20",
      type: "amateur",
      status: "upcoming",
      weightClasses: "All weight classes",
      entryDeadline: "2026-07-05",
      maxParticipants: 96,
      registeredCount: 43,
      entryFee: 3000,
      description: "Great tournament for debut fighters and seasoned amateurs from across the Lower Mainland and Fraser Valley.",
      contactEmail: "surreyboxing@bcboxing.ca",
    },
    {
      name: "Pacific Fight Night — Pro Showcase",
      city: "Vancouver",
      state: "BC",
      venue: "Hard Rock Casino Vancouver Theatre",
      startDate: "2026-09-20",
      type: "pro",
      status: "upcoming",
      weightClasses: "Lightweight, Welterweight, Middleweight, Heavyweight",
      entryDeadline: "2026-09-01",
      maxParticipants: 20,
      registeredCount: 14,
      entryFee: 0,
      description: "Western Canada's top professional fight card featuring regional title bouts. Promoted by Pacific Rim Promotions.",
      contactEmail: "bookings@pacificfightnight.ca",
      contactPhone: "(604) 555-0199",
    },
    {
      name: "Okanagan Valley Boxing Classic",
      city: "Kelowna",
      state: "BC",
      venue: "Prospera Place, Kelowna",
      startDate: "2026-08-08",
      endDate: "2026-08-09",
      type: "amateur",
      status: "upcoming",
      weightClasses: "Lightweight, Welterweight, Middleweight",
      entryDeadline: "2026-07-25",
      maxParticipants: 48,
      registeredCount: 29,
      entryFee: 2500,
      description: "Interior BC's top amateur showcase, drawing fighters from Kelowna, Kamloops, Vernon, and the Lower Mainland.",
      contactEmail: "okboxingclassic@gmail.com",
    },
    {
      name: "Fraser Valley Fight Nite",
      city: "Abbotsford",
      state: "BC",
      venue: "Abbotsford Centre",
      startDate: "2026-10-03",
      type: "pro",
      status: "upcoming",
      weightClasses: "Lightweight, Welterweight, Middleweight, Heavyweight",
      entryDeadline: "2026-09-15",
      maxParticipants: 16,
      registeredCount: 10,
      entryFee: 0,
      description: "Pro boxing returns to the Fraser Valley with a stacked card of local and national fighters.",
      contactEmail: "fvfightnite@bcboxing.ca",
      contactPhone: "(604) 555-0177",
    },
  ]);
  console.log("Inserted tournaments");

  console.log("✓ BC / Western Canada community seed complete");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
