-- Boxer AI club directory seed — generated from seed/clubs.json
-- Re-runnable: stable UUIDs from name+address, upserts on conflict.

insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('3ac4092f-4d63-530b-ae3d-b88e9bf7b1b0','Eastside Boxing Club','238 Keefer St, Vancouver, BC V6A 1X5','Vancouver',null,'604-620-0480',ARRAY['competitive amateur', 'fitness boxing', 'youth programs', 'women''s programs', 'nonprofit']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('7cc25b6d-f7aa-548b-8b73-0955dd0e4fc7','Quinit Boxing','1351 Grant St, Vancouver, BC V5L 2X7','Vancouver','https://www.quinitboxing.com','778-717-3833',ARRAY['competitive amateur', 'professional', 'youth programs', 'fitness boxing', 'sparring']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('9a7d2ad4-7f32-5e2e-8740-b967961f4395','Quinit Boxing','1180-573 Sherling Place, Port Coquitlam, BC','Port Coquitlam','https://www.quinitboxing.com','778-717-3833',ARRAY['competitive amateur', 'professional', 'youth programs', 'fitness boxing', 'sparring']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('a913443f-0f88-5493-8175-720abf376755','Griffins Boxing & Fitness','326 Esplanade E, North Vancouver, BC V7L 1A4','North Vancouver',null,'604-980-1900',ARRAY['fitness boxing', 'BoxFit program']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('41cbcffa-395a-5ef4-8e0d-b8a734ca8080','Sugarrays Boxing and Fitness','1738 W 3rd Ave, Vancouver, BC','Vancouver','https://sugarrays.com/','236-480-0064',ARRAY['fitness boxing']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('bdbc9d18-fc95-505a-947f-55d4708fc044','Sugarrays Boxing and Fitness','425 Front St, New Westminster, BC','New Westminster','https://sugarrays.com/','604-446-0890',ARRAY['fitness boxing']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('1ae94224-7abf-5945-99d3-e1e47c7b4f79','North Burnaby Boxing Club','5502 Lougheed Hwy, Burnaby, BC V5B 2Z8','Burnaby','http://www.bcboxers.com','778-709-7473',ARRAY['competitive amateur', 'youth programs']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('3dd0f689-3b2b-50e2-9c52-e46c5f180af2','Beyond Boxing','5544 Hastings St, Burnaby, BC V5B 1R3','Burnaby','https://beyondboxing.com/','604-809-5527',ARRAY['fitness boxing', 'technical boxing', 'open gym']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('4a76bbdc-f8b1-59f8-8613-47556c5ced2a','Astoria Boxing Club','1450 SW Marine Dr, Vancouver, BC (basement of Fraser Arms Hotel)','Vancouver',null,'604-802-2488',ARRAY['competitive amateur']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('fc2dd542-ffbd-5f22-a887-c91ef35b83af','30 Minute Hit','4-1801 Rosser Ave, Burnaby, BC V5C 6R4','Burnaby','https://www.30minutehit.com/locations/gym/burnaby-kickboxing-boxing-fitness.html','604-569-3737',ARRAY['women''s fitness boxing', 'kickboxing circuit']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('ce811dc3-9124-55f4-ba77-e8f9bb887be7','30 Minute Hit','108-5560 Minoru Blvd, Richmond, BC','Richmond','https://www.30minutehit.com','604-279-5425',ARRAY['women''s fitness boxing', 'kickboxing circuit']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('31adec07-fa00-519e-b924-6979c987ce84','Rumble Boxing','968 Expo Blvd, Vancouver, BC V6Z 2W1 (Yaletown)','Vancouver','https://rumbleboxing.com/','604-336-6939',ARRAY['fitness boxing']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('20a10f30-3f16-5213-82d8-4dd100135357','Rumble Boxing','168 Kingsway, Vancouver, BC V5T 3J2 (Mount Pleasant)','Vancouver','https://rumbleboxing.com/','604-336-6939',ARRAY['fitness boxing']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('c678614e-a088-5b3f-8e28-421c80a6f25f','Chilliwack Boxing Club','45680 Hocking Ave #201, Chilliwack, BC','Chilliwack','https://www.chilliwackboxingclub.com/',null,ARRAY['competitive amateur', 'youth programs', 'women''s programs', 'tournament host']::text[],true)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('7a3d0f26-9c85-57fc-b22d-2f395f8ca0b0','Boxing Vancouver','736 Granville St, Vancouver, BC','Vancouver','http://boxingvancouver.ca/','604-842-9810',ARRAY['fitness boxing']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('568d4c3c-fc14-59b3-9cee-2adc20c3c42d','Raincity Boxing and Fitness','8827 Selkirk St, Vancouver, BC V6P 4J6','Vancouver',null,'604-267-0365',ARRAY['fitness boxing', 'community gym']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('af856a1c-9ad2-55f5-b456-0edcaeed2962','Rock Steady Boxing','1807 W 1st Ave, Vancouver, BC V6J 5B8','Vancouver',null,'778-918-2475',ARRAY['fitness boxing']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('da52606d-717b-5b54-8882-e54c11ff919b','Pep Boxing & Fitness','516 Sharpe St, New Westminster, BC V3M 4R2','New Westminster',null,null,ARRAY['competitive amateur', 'professional']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('a0ac1589-4673-55a8-bce5-4a858e3be8c9','Unified Training Centre','11517 Kingston St, Maple Ridge, BC V2X 0Z5','Maple Ridge',null,null,ARRAY['fitness boxing', 'community gym', 'exhibitions']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('67773754-a98c-52ee-98e3-944d9203d177','Abbotsford Mission Boxing Club','28779 Maclure Rd, Abbotsford, BC V4X 1N1','Abbotsford',null,'604-826-1455',ARRAY['competitive amateur']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('78480ef4-43de-5b59-b88a-e51c04b77092','Mendoza Boxing Ltd','107-8645 160 St, Surrey, BC V4N 1G4','Surrey',null,'236-598-9471',ARRAY['fitness boxing']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('12477af0-c635-5bf1-839f-e9649a9ecdf1','BOX 2 FIT','1160 King George Blvd, Surrey, BC V4A 4Z2','Surrey',null,'778-384-6284',ARRAY['fitness boxing']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('0e929272-c821-51f6-9cc2-439561b2241c','Dream Fighters Canada','3470 E Hastings St, Vancouver, BC V5K 2A6','Vancouver',null,'778-814-6457',ARRAY['fitness boxing']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('ce81a366-009b-5b67-8d2e-f2ed0c0bc394','Honor Athletics','1771 Robson St, Vancouver, BC V6E 1C1','Vancouver',null,null,ARRAY['private boxing lessons', 'personal training']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('9831e696-d64d-5abd-aa48-acdd8d2eba04','Contenders Training Studio','1055 Dunsmuir St, Vancouver, BC V7X 1L3','Vancouver',null,null,ARRAY['fitness boxing']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('7742a8f4-0393-5a79-8f02-8d15543f2465','Diaz Combat Sports','Pender St, Vancouver, BC (exact address not verified)','Vancouver',null,null,ARRAY['competitive amateur', 'professional', 'fitness boxing']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('127b5653-2668-5d2f-b81f-00c7abd90aa6','Sparta Boxing and Fitness','2916 Graveley St, Vancouver, BC V5K 3K3','Vancouver',null,null,ARRAY['fitness boxing']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('8ecdfaed-f414-542a-b4b7-89921de849f8','BLK BOX GYM','133-12838 Clarke Place, Richmond, BC','Richmond',null,null,ARRAY['fitness boxing']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('12d40d29-9b04-5937-84c3-e558183035ba','Action Boxing Club',null,'West Vancouver',null,'604-922-4038',ARRAY['competitive amateur']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
insert into public.clubs (id,name,address,city,website,phone,specialties,verified) values ('7735ea7d-4498-592a-b34c-59ee3d7a9991','Titan Fitness (Savard Boxing)',null,'Surrey',null,null,ARRAY['competitive amateur']::text[],false)
  on conflict (id) do update set name=excluded.name, address=excluded.address, city=excluded.city, website=excluded.website, phone=excluded.phone, specialties=excluded.specialties, verified=excluded.verified;
